Repository AUTOINVEN/autoinven, pull requests merged in 2021-08, with the labels that each got.

#119 Enhancement/110 spacing adjust
  Public/CSS/iot.css
  Public/CSS/master.css
  Routes/pv.js
  Views/Iot/help.ejs
  Views/User/Buyer/by_RequestStatus.ejs
  Views/User/Provider/pv_MyWH.ejs
  Views/User/Provider/pv_WHinfo.ejs
  Views/User/user_Help.ejs
  Views/User/user_Show.ejs
Labels: UI, enhancement

#120 Feature/106 iot server split
  Public/JS/ad_requestIoT.js
  Public/JS/monitoring.js
  Routes/ad.js
  Routes/ad_RequestIoT.js
  Routes/ad_iotTest.js
  Routes/iot.js
  Routes/iot_monitoring.js
  Routes/iot_mypage.js
  Views/Iot/monitoring.ejs
  Views/User/Admin/ad_RequestIoT.ejs
  Views/User/Admin/ad_iotTest.ejs
Labels: enhancement

#122 fix: modify sql
  Routes/pv_MyWH.js
Labels: bug

#124 refactor: cleanup head.ejs
  Views/head.ejs
Labels: enhancement

#125 Feature/111-modify UI of buyer search warehouse
  Public/CSS/new_styles.css
  Public/JS/findWH.js
  Views/User/Buyer/by_FindWH.ejs
Labels: UI

#128 style: fix login UI
  Public/CSS/bootstrap.css
  Public/CSS/master.css
Labels: UI, enhancement

#129 fix: delete the top-margins in login & signup page
  Public/CSS/master.css
  Views/User/user_Login.ejs
  Views/User/user_Register.ejs
Labels: bug

#131 style: hilight logout button
  Public/CSS/master.css
  Views/User/user_Login.ejs
  Views/nav_Bar.ejs
Labels: UI

#132 Feat/127 rfid api
  Routes/iot.js
  Routes/iot_rfid.js
  raspi/account.js
  raspi/apollo.js
  raspi/app.js
  raspi/posts.js
Labels: enhancement, feature

#133 feat: add footer to all pages & add margins to bottom of pages
  Public/CSS/bootstrap.css
  Public/CSS/master.css
  Public/CSS/new_styles.css
  Views/User/Admin/ad_ContractInfo.ejs
  Views/User/Admin/ad_Question.ejs
  Views/User/Admin/ad_RequestBuy.ejs
  Views/User/Admin/ad_RequestEnroll.ejs
  Views/User/Admin/ad_RequestIoT.ejs
  Views/User/Admin/ad_iotTest.ejs
  Views/User/Buyer/by_FindWH.ejs
  Views/User/Buyer/by_RequestStatus.ejs
  Views/User/Buyer/by_UsageStatus.ejs
  Views/User/Provider/pv_EnrollWH.ejs
  Views/User/Provider/pv_MyWH.ejs
  Views/User/Provider/pv_WHinfo.ejs
  Views/User/user_Delete.ejs
  Views/User/user_Edit.ejs
  Views/User/user_Help.ejs
  Views/User/user_Login.ejs
  Views/User/user_PwEdit.ejs
  Views/User/user_Register.ejs
  Views/User/user_Show.ejs
  Views/footer.ejs
  Views/main_Home.ejs
Labels: UI, enhancement

#134 Feature/114 by usage
  Public/CSS/new_styles.css
  Public/JS/date.js
  Public/Upload/testAdmin_1627979838603.png
  Routes/by.js
  Routes/by_UsageInfo.js
  Routes/by_UsageStatus.js
  Views/User/Buyer/by_UsageInfo.ejs
  Views/User/Buyer/by_UsageStatus.ejs
Labels: enhancement, feature

#138 Feature/135 wh enroll req
  Public/JS/enrollWH.js
  Public/JS/findWH.js
  Routes/by_FindWH.js
  Routes/pv_EnrollWH.js
  Views/User/Admin/ad_RequestEnroll.ejs
  Views/User/Buyer/by_FindWH.ejs
  Views/User/Provider/pv_EnrollWH.ejs
Labels: enhancement, feature

#136 feat: modify MyInfo Page UI & fix PwEdit Bug
  Public/CSS/bootstrap.css
  Public/CSS/master.css
  Views/User/Buyer/by_FindWH.ejs
  Views/User/user_Edit.ejs
  Views/User/user_PwEdit.ejs
  Views/User/user_Show.ejs
Labels: UI, bug

#142 Enhancement/140 wh enroll UI
  Public/JS/enrollWH.js
  Views/User/Provider/pv_EnrollWH.ejs
Labels: UI, enhancement

#144 Feature/143 dev env improve
  docker-compose.yml
  dockerfile
  package.json
  webserver.js
Labels: enhancement

#148 Bug/145-FindWH
  Views/User/Buyer/by_FindWH.ejs
Labels: bug

#149 add: add footer
  Views/Iot/editItem.ejs
  Views/Iot/help.ejs
  Views/Iot/monitoring.ejs
  Views/Iot/registerItem.ejs
  Views/Iot/warehousing.ejs
  Views/User/Buyer/by_UsageStatus.ejs
Labels: enhancement, UI

#153 Feature/139 ad usage history
  Routes/ad.js
  Routes/ad_ContractInfo.js
  Routes/ad_ContractInfoView.js
  Routes/iot_monitoring.js
  Views/User/Admin/ad_ContractInfo.ejs
  Views/User/Admin/ad_ContractInfoView.ejs
  Views/User/Admin/ad_RequestEnroll.ejs
Labels: enhancement, feature

#150 Feat/137-enhance overall UI
  Public/CSS/master.css
  Views/User/Admin/ad_ContractInfo.ejs
  Views/User/Admin/ad_RequestBuy.ejs
  Views/User/Admin/ad_RequestEnroll.ejs
  Views/User/Admin/ad_RequestIoT.ejs
  Views/User/Buyer/by_FindWH.ejs
  Views/User/Buyer/by_RequestStatus.ejs
  Views/User/Buyer/by_UsageStatus.ejs
  Views/User/Provider/pv_EnrollWH.ejs
  Views/User/Provider/pv_MyWH.ejs
  Views/User/Provider/pv_WHinfo.ejs
  Views/User/user_Edit.ejs
  Views/User/user_Help.ejs
  Views/User/user_Login.ejs
  Views/User/user_PwEdit.ejs
  Views/User/user_Register.ejs
  Views/User/user_Show.ejs
  Views/nav_Bar.ejs
Labels: enhancement, UI

#154 feat: add myinfo
  Views/nav_Bar.ejs
Labels: enhancement

#156 refactor: Refactoring by_UsageInfo.ejs
  Routes/by.js
  Routes/by_UsageInfo.js
  Views/User/Buyer/by_UsageInfo.ejs
Labels: enhancement

#157 Enhancement/147 edit iot
  Public/CSS/iot.css
  Views/Iot/editItem.ejs
  Views/Iot/help.ejs
  Views/Iot/monitoring.ejs
  Views/Iot/nav.ejs
  Views/Iot/registerItem.ejs
  Views/Iot/warehousing.ejs
Labels: enhancement, UI

#160 Feature/159 css refactor
  Public/CSS/bootstrap.css
  Public/CSS/iot.css
  Public/CSS/master.css
  Public/CSS/new_styles.css
  Public/fonts/nucleo-license.md
  Public/fonts/nucleo-outline.eot
  Public/fonts/nucleo-outline.ttf
  Public/fonts/nucleo-outline.woff
  Public/fonts/nucleo-outline.woff2
  Views/User/user_Login.ejs
  Views/head.ejs
Labels: enhancement

#163 fix: css bug
  Public/CSS/master.css
  Views/nav_Bar.ejs
Labels: bug

#165 fix: admin cannot access iot page bug
  Public/JS/ad_requestIoT.js
  Routes/ad_iotTest.js
  Views/User/Admin/ad_iotTest.ejs
Labels: bug

#170 Feature/115 pv usage
  Public/JS/date.js
  Routes/WHinfo.js
  Routes/pv.js
  Routes/viewInfo.js
  Views/User/Provider/pv_MyWH.ejs
  Views/User/Provider/pv_WHinfo.ejs
  Views/User/WHinfo.ejs
Labels: enhancement, feature

#171 fix: add footer errors & modify additional designs
  Public/CSS/iot.css
  Public/CSS/master.css
  Public/Upload/testProvider_1628130404787.jpg
  Views/Iot/editItem.ejs
  Views/Iot/help.ejs
  Views/Iot/index.ejs
  Views/Iot/monitoring.ejs
  Views/Iot/registerItem.ejs
  Views/Iot/warehousing.ejs
  Views/User/Admin/ad_ContractInfo.ejs
  Views/User/Admin/ad_ContractInfoView.ejs
  Views/User/Admin/ad_Question.ejs
  Views/User/Admin/ad_RequestBuy.ejs
  Views/User/Admin/ad_RequestEnroll.ejs
  Views/User/Admin/ad_RequestIoT.ejs
  Views/User/Admin/ad_iotTest.ejs
  Views/User/Buyer/by_FindWH.ejs
  Views/User/Buyer/by_RequestStatus.ejs
  Views/User/Buyer/by_UsageInfo.ejs
  Views/User/Buyer/by_UsageStatus.ejs
  Views/User/Provider/pv_EnrollWH.ejs
  Views/User/Provider/pv_MyWH.ejs
  Views/User/WHinfo.ejs
  Views/User/user_Edit.ejs
  Views/User/user_Help.ejs
  Views/User/user_Login.ejs
  Views/User/user_PwEdit.ejs
  Views/User/user_Register.ejs
  Views/User/user_Show.ejs
  Views/footer.ejs
  Views/head.ejs
Labels: bug, UI

#173 bug: restore deleted p tags
  Views/User/Buyer/by_FindWH.ejs
Labels: bug

#175 Enhancement/166 update main
  Public/CSS/master.css
  Routes/main.js
  Routes/main_Home.js
  Views/main_Home.ejs
Labels: enhancement, feature

#177 Feature/176 hide api key
  .gitignore
  Module/db.js
  Routes/user_EmailIDF.js
  Views/User/Buyer/by_FindWH.ejs
  Views/main_Home.ejs
  config/config.json
  config/mailconfig.js
  docker-compose.yml
  package.json
  webserver.js
Labels: enhancement

#181 fix: script tag
  Views/User/Buyer/by_RequestStatus.ejs
  Views/User/Provider/pv_EnrollWH.ejs
Labels: bug

#182 Feature/179 byad refactor
  Routes/WHEdit.js
  Routes/WHInfo.js
  Routes/ad.js
  Routes/ad_ContractInfoView.js
  Routes/ad_IotTest.js
  Routes/ad_UsageHistory.js
  Routes/ad_UsageHistoryInfo.js
  Routes/by.js
  Routes/by_UsageHistory.js
  Routes/by_UsageHistoryInfo.js
  Routes/by_UsageInfo.js
  Routes/iot.js
  Routes/iot_EditItem.js
  Routes/iot_Help.js
  Routes/iot_Monitoring.js
  Routes/iot_RFID.js
  Routes/iot_RegisterItem.js
  Routes/iot_Warehousing.js
  Routes/pv.js
  Routes/viewInfo.js
  Views/IoT/iot_EditItem.ejs
  Views/IoT/iot_Help.ejs
  Views/IoT/iot_Monitoring.ejs
  Views/IoT/iot_Nav.ejs
  Views/IoT/iot_RegisterItem.ejs
  Views/IoT/iot_Warehousing.ejs
  Views/Iot/index.ejs
  Views/Iot/nav.ejs
  Views/User/Admin/ad_IotTest.ejs
  Views/User/Admin/ad_RequestIoT.ejs
  Views/User/Admin/ad_UsageHistory.ejs
  Views/User/Admin/ad_UsageHistoryInfo.ejs
  Views/User/Buyer/by_UsageHistory.ejs
  Views/User/Buyer/by_UsageHistoryInfo.ejs
  Views/User/Provider/pv_MyWH.ejs
  Views/User/WHEdit.ejs
  Views/User/WHInfo.ejs
  Views/nav_Bar.ejs
  package-lock.json
Labels: enhancement

#184 Enhancement/158 unify button and table properties
  Public/CSS/master.css
  Routes/ad.js
  Routes/ad_IotTest.js
  Views/IoT/iot_EditItem.ejs
  Views/IoT/iot_RegisterItem.ejs
  Views/IoT/iot_Warehousing.ejs
  Views/User/Admin/ad_IotTest.ejs
  Views/User/Admin/ad_RequestBuy.ejs
  Views/User/Admin/ad_RequestEnroll.ejs
  Views/User/Admin/ad_RequestIoT.ejs
  Views/User/Admin/ad_UsageHistory.ejs
  Views/User/Admin/ad_UsageHistoryInfo.ejs
  Views/User/Buyer/by_FindWH.ejs
  Views/User/Buyer/by_RequestStatus.ejs
  Views/User/Buyer/by_UsageHistory.ejs
  Views/User/Buyer/by_UsageHistoryInfo.ejs
  Views/User/Provider/pv_EnrollWH.ejs
  Views/User/Provider/pv_MyWH.ejs
  Views/User/user_Edit.ejs
  Views/User/user_PwEdit.ejs
  Views/User/user_Show.ejs
Labels: feature, UI

#186 feat: Show pv info only to admin
  Routes/ad.js
  Routes/ad_IoTTest.js
  Views/User/Admin/ad_IoTTest.ejs
  Views/User/WHInfo.ejs
Labels: enhancement

#189 Enhancement/167 separate signup step
  Public/CSS/master.css
  Public/JS/signUP.js
  Routes/user.js
  Views/User/user_Login.ejs
  Views/User/user_Register.ejs
  Views/User/user_Select.ejs
  Views/main_Home.ejs
  Views/nav_Bar.ejs
Labels: enhancement, feature

#193 Feature/187 re alert
  Public/CSS/master.css
  Public/JS/ad_RequestBuy.js
  Public/JS/ad_RequestEnroll.js
  Public/JS/ad_RequestIoT.js
  Public/JS/ad_requestIoT.js
  Public/JS/by_RequestStatus.js
  Public/JS/editWH.js
  Public/JS/enrollWH.js
  Public/JS/findWH.js
  Public/JS/login.js
  Public/JS/pv_MyWH.js
  Public/JS/signUP.js
  Routes/ad.js
  Routes/pv_MyWH.js
  Routes/viewInfo.js
  Views/User/Admin/ad_IoTTest.ejs
  Views/User/Admin/ad_RequestBuy.ejs
  Views/User/Admin/ad_RequestEnroll.ejs
  Views/User/Buyer/by_RequestStatus.ejs
  Views/User/Provider/pv_MyWH.ejs
Labels: enhancement

#194 feat: Change Google Map API KEY and Hide Geocoding Key
  Views/User/Buyer/by_FindWH.ejs
  Views/User/Provider/pv_EnrollWH.ejs
  Views/User/WHEdit.ejs
  Views/main_Home.ejs
  package-lock.json
Labels: enhancement

#195 Feat/190 update main page and signup page UI
  Public/CSS/master.css
  Public/Image/warehouse-buyer.png
  Public/Image/warehouse-provider.png
  Views/User/Buyer/by_FindWH.ejs
  Views/User/Provider/pv_EnrollWH.ejs
  Views/User/user_Edit.ejs
  Views/User/user_Login.ejs
  Views/User/user_Register.ejs
  Views/User/user_Select.ejs
  Views/User/user_Show.ejs
  Views/footer_forMain.ejs
  Views/main_Home.ejs
Labels: UI

#198 change: change link about login/signup
  Views/User/user_Select.ejs
  Views/main_Home.ejs
  Views/nav_Bar.ejs
  package-lock.json
Labels: enhancement

#205 Bug/203 IoT nav bug
  Routes/iot.js
Labels: bug

#206 Feature/204 separate menu
  Views/nav_Bar.ejs
Labels: feature

#208 Feature/188 rej handling
  Public/JS/ad_RequestBuy.js
  Public/JS/ad_RequestEnroll.js
  Public/JS/ad_RequestIoT.js
  Public/JS/alerts.js
  Public/JS/by_RequestStatus.js
  Public/JS/date.js
  Public/JS/pv_MyWH.js
  Routes/WHInfo.js
  Routes/ad_RequestBuy.js
  Routes/ad_RequestEnroll.js
  Routes/ad_RequestIoT.js
  Routes/by_RequestStatus.js
  Routes/by_UsageHistory.js
  Routes/pv.js
  Routes/pv_MyWH.js
  Views/User/Admin/ad_IoTTest.ejs
  Views/User/Admin/ad_RequestBuy.ejs
  Views/User/Admin/ad_RequestEnroll.ejs
  Views/User/Admin/ad_RequestIoT.ejs
  Views/User/Buyer/by_RequestStatus.ejs
  Views/User/Provider/pv_MyWH.ejs
  raspi/account.js
Labels: enhancement, feature

#210 Feature/209 wh info bug
  Routes/WHEdit.js
  Routes/ad_RequestEnroll.js
  Routes/ad_RequestIoT.js
  Routes/pv.js
  Routes/pv_MyWH.js
  Views/User/Admin/ad_RequestEnroll.ejs
  Views/User/Admin/ad_RequestIoT.ejs
Labels: bug

#214 Feature/207 divide help
  Public/CSS/master.css
  Views/User/user_Help.ejs
Labels: feature, UI

#217 Feature/216 public warehouse
  Public/JS/findWH.js
  Routes/by.js
  Routes/by_FindWH.js
  Routes/main.js
  Routes/main_Home.js
  Views/User/Buyer/by_FindWH.ejs
  Views/main_Home.ejs
Labels: enhancement

#218 Enhancement/213 enhance login
  Public/CSS/master.css
Labels: UI

#223 Enhancement/215 enhance help
  Public/CSS/master.css
  Views/User/user_Help.ejs
Labels: enhancement, UI

#226 fix: RFID bug
  Routes/iot_RFID.js
  raspi/posts.js
Labels: bug

#230 fix: admin IoT page bug
  Routes/iot_Monitoring.js
Labels: bug

#231 Feature/219 show wh enroll
  Public/JS/ad_RequestEnroll.js
  Public/Upload/testProvider_1629157516019.png
  Public/Upload/testProvider_1629158962326.png
  Public/Upload/testProvider_1629159933057.png
  Public/Upload/testProvider_1629168265394.png
  Public/Upload/testProvider_1629176738732.png
  Routes/EnrollWHInfo.js
  Routes/ad.js
  Routes/pv.js
  Views/User/Admin/ad_RequestEnroll.ejs
  Views/User/EnrollWHInfo.ejs
  Views/User/Provider/pv_MyWH.ejs
  Views/User/WHInfo.ejs
Labels: enhancement

#232 fix: admin rej enroll bug
  Routes/ad_RequestEnroll.js
Labels: bug

#236 Enhancement/222 overall UI
  Views/User/Admin/ad_RequestEnroll.ejs
  Views/User/Provider/pv_EnrollWH.ejs
  Views/User/Provider/pv_MyWH.ejs
  Views/nav_Bar.ejs
Labels: enhancement, UI

#237 Feature/220 show request
  Routes/RequestWHInfo.js
  Routes/ad.js
  Routes/by.js
  Routes/pv.js
  Views/User/Admin/ad_RequestBuy.ejs
  Views/User/Admin/ad_RequestEnroll.ejs
  Views/User/Buyer/by_RequestStatus.ejs
  Views/User/Provider/pv_MyWH.ejs
  Views/User/RequestWHInfo.ejs
Labels: enhancement

#238 Update: Links in MainPage
  Public/CSS/master.css
  Views/User/WHInfo.ejs
  Views/main_Home.ejs
  Views/nav_Bar.ejs
Labels: feature

#245 feat: Show WH, PV data at RequestIot (admin)
  Public/Upload/testAdmin_1629252544552.png
  Routes/IoTWHInfo.js
  Routes/ad.js
  Views/User/Admin/ad_RequestEnroll.ejs
  Views/User/Admin/ad_RequestIoT.ejs
  Views/User/IoTWHInfo.ejs
  Views/User/Provider/pv_MyWH.ejs
Labels: enhancement, feature

#247 Bug/246 cnl rej state
  Views/User/Admin/ad_RequestBuy.ejs
  Views/User/Admin/ad_RequestIoT.ejs
  Views/User/Buyer/by_RequestStatus.ejs
  Views/User/Provider/pv_MyWH.ejs
Labels: bug

#248 fix: Fix reject button error in pv MyWH page
  Views/User/Provider/pv_MyWH.ejs
Labels: bug

#250 fix pv_MyWH page table button margin
  Views/User/Provider/pv_MyWH.ejs
Labels: bug, UI

#251 fix: Hide IoT btn when selected warehouse doesn't use IoT service.
  Routes/viewInfo.js
  Views/User/WHInfo.ejs
Labels: bug

#252 update: add modal to contact admin
  Views/User/Buyer/by_FindWH.ejs
Labels: feature

#253 Bug/211 sign up bug
  Public/JS/signUP.js
  Routes/user_Register.js
  Views/User/user_Register.ejs
Labels: bug, enhancement

#255 Feature/243 IoT 페이지의 Item Edit과 Register에 관련된 버그 수정과 사용성 개선
  Routes/iot.js
  Routes/iot_EditItem.js
  Routes/iot_RegisterItem.js
  Views/IoT/iot_EditItem.ejs
  Views/IoT/iot_RegisterItem.ejs
  Views/IoT/iot_Warehousing.ejs
Labels: bug, enhancement

#258 Feature/254 bugfix
  Public/CSS/master.css
  Public/JS/ad_RequestIoT.js
  Public/JS/alerts.js
  Public/JS/findWH.js
  Public/JS/pv_MyWH.js
  Routes/WHEdit.js
  Views/User/Buyer/by_FindWH.ejs
  Views/User/Buyer/by_RequestStatus.ejs
  Views/User/Provider/pv_MyWH.ejs
  Views/main_Home.ejs
Labels: bug

#260 fix: modal errors
  Views/User/Admin/ad_WarehouseList.ejs
  Views/User/WHInfo.ejs
Labels: bug

#261 Bug/141 amount
  Public/JS/by_RequestStatus.js
  Public/JS/findWH.js
  Public/Upload/testProvider_1629348452042.png
  Routes/RequestWHInfo.js
  Routes/WHEdit.js
  Routes/WHInfo.js
  Routes/ad_RequestBuy.js
  Routes/ad_UsageHistory.js
  Routes/by_FindWH.js
  Routes/by_RequestStatus.js
  Routes/by_UsageHistory.js
  Routes/iot_Monitoring.js
  Routes/pv_EnrollWH.js
  Routes/pv_MyWH.js
  Views/User/Admin/ad_RequestBuy.ejs
  Views/User/Admin/ad_UsageHistory.ejs
  Views/User/Admin/ad_UsageHistoryInfo.ejs
  Views/User/Buyer/by_RequestStatus.ejs
  Views/User/Buyer/by_UsageHistory.ejs
  Views/User/Buyer/by_UsageHistoryInfo.ejs
  Views/User/RequestWHInfo.ejs
  Views/User/WHInfo.ejs
Labels: bug, enhancement, feature

#262 Enhancement/244 update iot help
  Views/IoT/iot_Help.ejs
Labels: enhancement

#265 fix: signup page js
  Public/JS/signUP.js
Labels: bug

#269 Feature/162 update help
  Public/CSS/master.css
  Public/Image/Help_Diagram.jpg
  Views/User/user_Help.ejs
Labels: enhancement, UI

#270 unify all names and columns
  Public/CSS/master.css
  Views/User/Admin/ad_RequestIoT.ejs
  Views/User/Admin/ad_UsageHistory.ejs
  Views/User/Admin/ad_UsageHistoryInfo.ejs
  Views/User/Admin/ad_WarehouseList.ejs
  Views/User/Buyer/by_FindWH.ejs
  Views/User/Buyer/by_RequestStatus.ejs
  Views/User/Buyer/by_UsageHistory.ejs
  Views/User/Buyer/by_UsageHistoryInfo.ejs
  Views/User/EnrollWHInfo.ejs
  Views/User/IoTWHInfo.ejs
  Views/User/Provider/pv_EnrollWH.ejs
  Views/User/Provider/pv_MyWH.ejs
  Views/User/RequestWHInfo.ejs
  Views/User/WHEdit.ejs
  Views/User/WHInfo.ejs
  Views/User/user_Edit.ejs
  Views/User/user_Show.ejs
  Views/main_Home.ejs
Labels: enhancement

#275 fix: Fix info page access error
  Views/User/RequestWHInfo.ejs
Labels: bug

#278 fix: Fix enroll warehouse error
  Routes/pv_EnrollWH.js
Labels: bug

#277 Feature/274 myinfo email
  Public/JS/signUP.js
  Public/JS/user_Edit.js
  Routes/user_Edit.js
  Views/User/user_Edit.ejs
  Views/User/user_Register.ejs
Labels: bug

#283 [#280] 창고 신청 오류
  Public/JS/findWH.js
  Views/User/Buyer/by_FindWH.ejs
Labels: bug

#284 [#282] 창고 결제 오류
  Public/JS/by_RequestStatus.js
Labels: bug

#287 [#286] 아두이노 코드 추가
  HW/ArduinoSensor/Arduino_Sensor.ino
  HW/Raspi/account.js
  HW/Raspi/apollo.js
  HW/Raspi/app.js
  HW/Raspi/posts.js
Labels: enhancement, feature
