Repository AUTOINVEN/autoinven, pull requests merged in 2021-07, with the labels that each got.

#23 feat: Show item in proper Warehouse
  Routes/iot_warehousing.js
Labels: enhancement

#25 feat: Show alert inaccessible page
  Routes/ad.js
  Routes/by.js
  Routes/iot.js
  Routes/pv.js
  Routes/user.js
  Views/Alert/cannotAccess.ejs
  Views/Alert/needLogin.ejs
  Views/Iot/unauthorized.ejs
  webserver.js
Labels: bug, enhancement

#26 feat: integrated UI design of autoin iot
  Public/CSS/iot.css
  Public/CSS/master.css
  Public/CSS/new_styles.css
  Routes/iot.js
  Routes/iot_help.js
  Routes/iot_statistics.js
  Routes/user.js
  Views/Alert/cannotAccess.ejs
  Views/Alert/needLogin.ejs
  Views/Iot/monitoring.ejs
  Views/Iot/mypage.ejs
  Views/Iot/nav.ejs
  Views/Iot/registerItem.ejs
  Views/Iot/statistics.ejs
  Views/Iot/warehousing.ejs
  Views/User/Provider/pv_MyWH.ejs
  package.json
  webserver.js
Labels: UI, enhancement

#34 feat: Sequential wid number
  Public/JS/enrollWH.js
  Routes/pv_EnrollWH.js
  Views/User/Provider/pv_EnrollWH.ejs
Labels: enhancement

#38 Revert "fix: referer bug"
  Routes/iot.js
Labels: bug

#42 Feature/39 js alert to sweetalert
  Public/JS/enrollWH.js
  Public/JS/login.js
  Public/JS/signUP.js
  Views/User/Admin/ad_RequestBuy.ejs
  Views/User/Admin/ad_RequestEnroll.ejs
  Views/User/Admin/ad_RequestIoT.ejs
  Views/User/Buyer/by_FindWH.ejs
  Views/User/Buyer/by_MyWH.ejs
  Views/User/Provider/pv_MyWH.ejs
  Views/User/user_Edit.ejs
  Views/User/user_Show.ejs
Labels: UI, enhancement

#52 Bug/41 search warehouse
  Public/JS/signUP.js
  Public/Upload/1626744527400.png
  Public/Upload/1626744539532.png
  Public/Upload/1626744560267.png
  Routes/ad_ContractInfo.js
  Routes/ad_RequestEnroll.js
  Routes/ad_RequestIoT.js
  Routes/pv.js
  Routes/pv_EnrollWH.js
  Routes/pv_MyWH.js
  Routes/user_Delete.js
  Routes/user_Edit.js
  Routes/user_Login.js
  Routes/user_Register.js
  Views/User/Admin/ad_ContractInfo.ejs
  Views/User/Admin/ad_RequestEnroll.ejs
  Views/User/Admin/ad_RequestIoT.ejs
  Views/User/Buyer/by_FindWH.ejs
  Views/User/Provider/pv_MyWH.ejs
  Views/User/user_Edit.ejs
  Views/User/user_Register.ejs
  Views/User/user_Show.ejs
  package-lock.json
  package.json
Labels: bug, enhancement

#63 style: adjust space not needed
  Public/CSS/master.css
  Views/User/Admin/ad_ContractInfo.ejs
  Views/User/Admin/ad_RequestBuy.ejs
  Views/User/Admin/ad_RequestEnroll.ejs
  Views/User/Admin/ad_RequestIoT.ejs
  Views/User/Buyer/by_FindWH.ejs
  Views/User/Provider/pv_EnrollWH.ejs
  Views/User/Provider/pv_MyWH.ejs
  Views/User/user_Help.ejs
  Views/User/user_Show.ejs
Labels: UI

#64 Feature/31 modify my warehouse UI
  Public/CSS/new_styles.css
  Public/Upload/1626624001828.jpg
  Public/Upload/1626625985817.jpg
  Public/Upload/1626633606670.jpg
  Public/Upload/1626637085477.jpg
  Views/User/Provider/pv_MyWH.ejs
  package.json
Labels: UI, enhancement

#66 fix: Admin RequestIOT Table Layout
  Views/User/Admin/ad_RequestIoT.ejs
Labels: UI

#69 Feature/68 refactor bug
  Views/User/Provider/pv_EnrollWH.ejs
  Views/User/user_Edit.ejs
  Views/User/user_Show.ejs
Labels: bug

#71 enhancement: upgrading help page
  Public/CSS/master.css
  Public/Upload/testProvider_1627005705216.jpg
  Views/User/user_Help.ejs
Labels: UI, enhancement

#73 Enhancement/62 upgrade signin
  Views/User/user_Register.ejs
Labels: UI

#74 Feature/72 language into English
  Public/JS/login.js
  Public/JS/monitoring.js
  Public/Upload/testProvider_1626998477421.jpg
  Routes/iot_statistics.js
  Views/Alert/cannotAccess.ejs
  Views/Alert/needLogin.ejs
  Views/Iot/editItem.ejs
  Views/Iot/help.ejs
  Views/Iot/index.ejs
  Views/Iot/monitoring.ejs
  Views/Iot/nav.ejs
  Views/Iot/registerItem.ejs
  Views/Iot/statistics.ejs
  Views/Iot/warehousing.ejs
  Views/User/Admin/ad_ContractInfo.ejs
  Views/User/Admin/ad_RequestBuy.ejs
  Views/User/Admin/ad_RequestEnroll.ejs
  Views/User/Admin/ad_RequestIoT.ejs
  Views/User/Buyer/by_FindWH.ejs
  Views/User/Buyer/by_MyWH.ejs
  Views/User/Provider/pv_EnrollWH.ejs
  Views/User/Provider/pv_MyWH.ejs
  Views/User/user_Edit.ejs
  Views/User/user_EmailIDF.ejs
  Views/User/user_Help.ejs
  Views/User/user_Login.ejs
  Views/User/user_PwEdit.ejs
  Views/User/user_Register.ejs
  Views/User/user_Show.ejs
  Views/footer.ejs
  Views/head.ejs
  Views/main_Home.ejs
  Views/nav_Bar.ejs
Labels: UI

#79 feature: add iot help page
  Public/Image/iot_help1.PNG
  Public/Image/iot_help2.PNG
  Routes/iot_help.js
  Views/Iot/help.ejs
  Views/User/user_Help.ejs
Labels: feature

#82 feat:change container size, fix page-header css
  Public/CSS/bootstrap.css
  Public/CSS/master.css
  Views/User/Admin/ad_ContractInfo.ejs
  Views/User/Admin/ad_RequestBuy.ejs
  Views/User/Admin/ad_RequestEnroll.ejs
  Views/User/Admin/ad_RequestIoT.ejs
  Views/User/Buyer/by_FindWH.ejs
  Views/User/Buyer/by_MyWH.ejs
  Views/User/Provider/pv_EnrollWH.ejs
  Views/User/Provider/pv_MyWH.ejs
  Views/User/user_Edit.ejs
  Views/User/user_Help.ejs
  Views/User/user_PwEdit.ejs
  Views/User/user_Show.ejs
  Views/head.ejs
Labels: UI, feature

#85 Feature/61-authority
  Routes/iot.js
  Routes/iot_warehousing.js
  Views/Iot/warehousing.ejs
Labels: enhancement

#87 Feature/80 add whinfo
  Routes/iot.js
  Routes/pv.js
  Routes/pv_MyWH.js
  Views/User/Provider/pv_MyWH.ejs
  Views/User/Provider/pv_WHinfo.ejs
Labels: feature

#90 fix: Date validation check
  Public/JS/findWH.js
  Views/User/Buyer/by_FindWH.ejs
Labels: bug, enhancement

#98 enhancement: add warehouse information area and iot button
  Views/User/Provider/pv_WHinfo.ejs
Labels: enhancement

#100 Feature/93 db refactor
  Routes/ad_ContractInfo.js
  Routes/by_MyWH.js
  Routes/pv_MyWH.js
  Views/User/Admin/ad_ContractInfo.ejs
  Views/User/Buyer/by_MyWH.ejs
  Views/User/Provider/pv_MyWH.ejs
Labels: enhancement

#101 fix: Create fake pay button
  Views/User/Buyer/by_MyWH.ejs
Labels: enhancement

#103 Feature/94-contactWH
  Public/JS/enrollWH.js
  Public/JS/findWH.js
  Public/Upload/testProvider_1627548229414.png
  Public/Upload/testProvider_1627608185360.png
  Routes/by_FindWH.js
  Routes/pv_EnrollWH.js
  Views/User/Admin/ad_ContractInfo.ejs
  Views/User/Buyer/by_FindWH.ejs
  Views/User/Provider/pv_EnrollWH.ejs
Labels: enhancement, feature

#112 modify: change dropdown toggle button's direction
  Views/nav_Bar.ejs
Labels: enhancement

#118 fix: routing errors
  Public/JS/findWH.js
  Routes/by.js
  Routes/by_RequestStatus.js
  Routes/by_UsageStatus.js
  Routes/iot.js
  Views/User/Buyer/by_UsageStatus.ejs
Labels: bug
